services:
  - type: web
    name: stock_getter
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn stock_getter.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4